[tool.poetry]
name = "jade"
version = "0.1.0"
description = ""
authors = ["C. Thomas Brittain <thomasb@bitfocus.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
